# Generated by Django 3.2.20 on 2023-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='default_image.jpg', upload_to='static/images')),
                ('category', models.CharField(choices=[('L', 'lunch'), ('B', 'breakfast'), ('D', 'dinner')], max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
