# Generated by Django 4.2.3 on 2023-07-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_delivered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
